version: "2"

run:
  timeout: "5m"

linters:
  default: standard
  enable:
    - exhaustruct
    - gosec
    - revive
    - misspell
    - gocritic

  settings:
    exhaustruct:
      include:
        - "github\\.com/larsartmann/go-idempotency\\..*"
